### ISSUE TITLE
can't move in menu

### ISSUE THREAD

**Issue by SuperROBO-1** [dots-tb/LOLIcon#1]
pretty self explanatory, i can open and close the lolicon menu just fine, but cannot move up or down to any options while in it

Im on 3.68 hencore, using a PSTV

**Comment by Memory10969** [comment]
I meet the bug too,i can open and close it , but just that .
looks like it just happen on 3.68 ,please fix it

**Comment by Thekenbaum** [comment]
I ran into this problem as well.

**Comment by dots-tb** [comment]
Alright, check the new release.

**Comment by Alexr1110** [comment]
I think is a bug, I can't use adrenaline, it doesn't start
