### ISSUE TITLE
Games stuck on splash screen

### ISSUE THREAD

**Issue by masterrite** [dots-tb/LOLIcon#10]
Games like YS VIII asian version gets stuck on the  splash screen. Might just be the game requiring too much Ram or something.

**Comment by dots-tb** [comment]
Does it work on the non test-build or is that on the release build? I don't think there is anything too memory intensive with LOLIcon...

**Comment by masterrite** [comment]
Could also be ioplus.skprx though. I diasabled lolicon completely and re uploaded game files, the game still gets stuck. It's my own dump so I'm sure the dump is fine

**Comment by masterrite** [comment]
OK problem solved. It's ioplus.skprx's fault. Changed that to kuio.skprx and the game started.

**Comment by dots-tb** [comment]
ioPlus is not needed for LOLIcon and is only needed for userplugins. These userplugins must be updated to use ioPlus.

**Comment by masterrite** [comment]
Thanks dots!
 
I can't think of which plugin it is though. All I did was switching back to kuio.
