### ISSUE TITLE
Not really a big problem, but...

### ISSUE THREAD

**Issue by EulenCarbon** [dots-tb/LOLIcon#11]
![12ac2e8613a790e61a26f3a7c58505d9](https://user-images.githubusercontent.com/42668474/44619313-fb64c680-a8b6-11e8-80b7-e67c0a7af0b6.png)
Well, each time I start a game or exit the sleep mode, these green things: Configuration loaded  always come up.
I know it's not something really serious,but, you know, I just want to figure out whether it's a glitch.
Sorry for I'm suffering OCD, anyway, thank you for your work.

**Comment by dots-tb** [comment]
You can disable them on the test build by doing a clear settings, then going to the OSD settings, checking hide, and saving a default profile.

**Comment by Jlroxy** [comment]
it is still there even after i follow your method, Mine is "configuration loaded : 4"

**Comment by Jlroxy** [comment]
It is also popping-up when you play YouTube videos, kind a annoying to see..

**Comment by Jlroxy** [comment]
Nevermind I got it working now, by saving as main instead of saving it as default
