### ISSUE TITLE
【bug】It stuck when you turn on the 500Mhz mode

### ISSUE THREAD

**Issue by EulenCarbon** [dots-tb/LOLIcon#14]
I just stuck when I started 'Carton fighter W' in 500Mhz mode, I can only start it normally in 444Mhz mode or lower.

**Comment by masterrite** [comment]
Are you using ioplus.skprx? Switch back to kuio.skprx and see. 
 
I had almost the same issue with ys viii, but mine was the whole game gets stuck on the splash screen regardless the clock. It's fixed once I switched back to kuio.

**Comment by wfcntrl** [comment]
I had the same issue with YS VIII as masterrite mentioned. Although i was playing the maidump jp version. Removing ioplus from tai config fixed mine too.

**Comment by dots-tb** [comment]
LOLIcon does not need ioPlus nor kuio, LOLIcon runs in the kernel. Please refer to the release notes of the latest prerelease.

**Comment by wfcntrl** [comment]
Sorry. I didnt know it doesnt have dependency for io. Autoplugin had it bundled with the installation of LOLIcon.
