### ISSUE TITLE
There was a problem loading. 3

### ISSUE THREAD

**Issue by OMGitsHYPER** [dots-tb/LOLIcon#15]
Hi,

First, I installed the plugin via AutoPlugin and PSVITA did reboot successfully. However, I kept getting "There was a problem loading. 3" error. After I removed the plugin; I downloaded it, placed the file and set up the taiHEN config manually. However, this time, I kept getting the aforementioned error on the epilepsy warning screen, preventing the PSVITA to boot to LiveArea and causing it to turn off.

PSVITA PCH-1104 3.65 Ensō installed

**Comment by dysprosi** [comment]
I have a similar problem. I repeatedly get the "There was a problem loading. : 3". I'm using a PCH-1101 3.68 using h-encore. It shows as soon as I run H-encore from a fresh reboot, starting any game/app, and when opening the LOLIcon menu.

**Comment by OMGitsHYPER** [comment]
I had the exact same problem as you, but it mutated into the problem I mostly explained above after re-installing the plugin.

**Comment by Darkshadow3582** [comment]
I have the same problem and solvet it, put the plugin line to the top, like this
*KERNEL
ur0/tai/lolicon.skprx

**Comment by dysprosi** [comment]
I tried that, and it didn't work. It doesn't matter where I have it listed.

**Comment by dots-tb** [comment]
There was a problem loading. : 3 just means that you need to save a default configuration. @Darkshadow3582 @OMGitsHYPER @dysprosi 

If its crashing, just create the folder ur0:LOLIcon. I will push a hot fix to do this in a few.

**Comment by OMGitsHYPER** [comment]
I created the folder ur0:LOLIcon but the problem persists.
I also tried;
creating ux0:LOLIcon, 
creating both, 
creating config.txt in ur0:LOLIcon, 
placing the plugin just a line below *KERNEL in config.txt,
installing the plugin in ur0:/tai.

**Comment by OMGitsHYPER** [comment]
As for "There was a problem. 3" error, I created a folder with the name LOLIcon in ur0: and selected "Save as Default" in the plugin's menu. It is resolved now.

Moreover, I found out the reason for my PSVITA not to be able to boot: LOLIcon + udcd_uvc.
I have no idea why, but when these two plugins are installed, my PSVITA cannot boot to LiveArea. When I disable one of them, the device boots successfully.

**Comment by Darkshadow3582** [comment]
I have both plugins and it works perfectly

I have the config like this
*KERNEL
ur0:tai/lolicon.skprx
....
....
....
ur0:tai/udcd_uvc.skprx

**Comment by OMGitsHYPER** [comment]
I just re-ordered the lines inside of the tai/config.txt according to your recommendation and the PSVITA booted to LiveArea without a single problem.

Thank you.

**Comment by dots-tb** [comment]
@OMGitsHYPER sorry that you had so many problems. :(

**Comment by paulo-lima-dev** [comment]
Are you guys sure this was fixed?
I'm still getting this error ;/

**Comment by Darkshadow3582** [comment]
In my case, yes fixed

**Comment by ghost** [comment]
> As for "There was a problem loading. 3" error, I created a folder with the name LOLIcon in ur0: and selected "Save as Default" in the plugin's menu. It is resolved now.
> 
> Moreover, I found out the reason for my PSVITA not to be able to boot: LOLIcon + udcd_uvc.
> I have no idea why, but when these two plugins are installed, my PSVITA cannot boot to LiveArea. When I disable one of them, the device boots successfully.

I am facing the same problem. How r you able to created folder in ur0 since your psvita keep turning off.?

**Comment by OMGitsHYPER** [comment]
@sophanith-github Hold L button while turning on the Vita.

**Comment by ghost** [comment]
@OMGitsHYPER u saved my day. thx

**Comment by Alteroku** [comment]
I can start menu but I can't navigate it...
