### ISSUE TITLE
Plugin make some game stuck on loading...

### ISSUE THREAD

**Issue by revildaron** [dots-tb/LOLIcon#19]
Hello, can you please fix this plugin to support game pcse00471 and pcse00376
For pcse00471 game stuck on loading while checking dlc...
For pcse00376 game dlc not detect after use this plugin...

**Comment by dots-tb** [comment]
Did you install using autoplugin? What's your config?

**Comment by revildaron** [comment]
Yes.

**Comment by revildaron** [comment]
![20180906_165519](https://user-images.githubusercontent.com/43037394/45194102-1af9d880-b241-11e8-9602-4aac97a43634.jpg)
![20180906_165531](https://user-images.githubusercontent.com/43037394/45194110-264d0400-b241-11e8-948d-33e989e338d0.jpg)

**Comment by dots-tb** [comment]
Please update autoplugin or delete ioplus.skprx. GAC has included the wrong ver of ioPlus.

**Comment by revildaron** [comment]
Briliant!! That works! Thanks dots-tb for this awesome plugin

**Comment by dots-tb** [comment]
You have a good one! :)
