### ISSUE TITLE
run adrenaline error

### ISSUE THREAD

**Issue by oleang01** [dots-tb/LOLIcon#3]
run adrenaline already error please Introduce me

**Comment by oleang01** [comment]
thanks you

**Comment by masterrite** [comment]
Adrenaline doesn't even start. Just gives a black screen and I had to restart vita through the recovery menu.

**Comment by kane159** [comment]
-1 here, seems that this plugin is not compatible with adrenaline

**Comment by simonizer2409** [comment]
Since it's a kernel plugin, you can't deactivate it for certain applications. So it's either use or don't use it.

Hopefully there will be a fix. Sticking to VSH Menu for now.

**Comment by dots-tb** [comment]
@oleang01 @masterrite @kane159 @simonizer2409 Please try this build and report back.
[LOLIcon.zip](https://github.com/dots-tb/LOLIcon/files/2320462/LOLIcon.zip)

**Comment by EulenCarbon** [comment]
Amazing man！Adrenaline now runs perfectly as usual（3.60, I haven't tested 3.68 yet），good job！

**Comment by Miyako09** [comment]
That build works great, Adrenaline works again on 3.65

**Comment by Thekenbaum** [comment]
Works on 3.68; now I can play my lower poly then usual anime waifu games again!
Don't judge me.

**Comment by oleang01** [comment]
Good work in 3.68 adrenaline.Thank you very much, you are God.

**Comment by masterrite** [comment]
Adrenaline works again, but I get this yellow message saying "There's an error loading...: 3". Pressing SELECT + UP still calls up LOLIcon's menu, however. Also, the fps boost I got for mGBA when playing FFVI advance yesterday on 500mHz is gone with this version. Not sure if the boost yesterday is legit now.

Thanks for you work though!

**Comment by simonizer2409** [comment]
@dots-tb Works great on 3.65 Henkaku/Enso. Thanks for the fix.

@masterrite The error message will only appear, if you have no saved config.

**Comment by Yoshideking** [comment]
I tested today Adrenaline, gonna check for this issue cuz needed to restart two times (one with a bubble created with Adrenaline Bubble Creator and one with Adrenaline itself) and BANG problem solved! Not even needed to complain about it.

Big thanks, dude! I'm loving this software, but gonna need a new battery.

**Comment by dots-tb** [comment]
Be sure to update to the pre-release build to fix adrenaline, the test build given above has some errors regarding this issue.
