### ISSUE TITLE
Error saving

### ISSUE THREAD

**Issue by noradninja** [dots-tb/LOLIcon#6]
I have not tested on my PSVita (testing with my VitaTV), but when I try to save (either as Default of for the particular app), `There was a problem saving          :   1` flashes at the top of the screen. Using SD2Vita as **ux0:**, **tai** is in **ur0:** if that makes a difference. There is a LOLIcon folder in **uma0:** also.

**Comment by TheRadziu** [comment]
might be vitatv related issue, for me on 3.65 enso regular vita it saves profiles just fine on microsd mounted as ux0, not on vita stick (uma0)

**Comment by noradninja** [comment]
I will see if I can replicate the issue with my Vita and try to narrow it down.

**Comment by noradninja** [comment]
Ok so on my Vita, which has a 4GB Sony card installed configured as **uma0:**, the save works and LOLIcon folder is in **ux0:** on the SD2Vita. Going to try editing storageconfig.cfg and disabling mapping the internal memory on the VitaTV as **uma0:** and see if the plugin will create the folder on **ux0:** and save its configuration there.

**Comment by noradninja** [comment]
@dots-tb 

Ok so the issue is with the VitaTV. Even after disabling **uma0:** on the VitaTV, the plugin still would not save configurations. I then manually created the LOLIcon folder on the VitaTV in **ux0:** then attempted to save a configuration, and it worked, even persisting across reboots. So the issue seems to be with the VItaTV and not properly creating the folder on **ux0:**, because aside from the platform, all other variables (Firmware version, SD2Vita version, even the SD card brand and size) are identical. 

![img_0442](https://user-images.githubusercontent.com/6692990/44601314-05e56a00-a7aa-11e8-8ecf-32a40c3981b4.jpeg)

**Comment by noradninja** [comment]
@dots-tb

SD2Vita loads first on both devices.

**Comment by CelesteBlue-dev** [comment]
@dots-tb I had told you to use ur0 and not ux0, because that's hard to manage for people who have many storage devices.

**Comment by itsminht** [comment]
^
Ahhh two phenomenal Vita hb devs arguing over the details of a plugin they developed. Brilliant :D

**Comment by noradninja** [comment]
@kong2991

Make sure you only have one tai/config.txt otherwise they will conflict. I suggest putting it in ur0: then making sure your plugins are also there, and editing your config to reflect that. In my case I had to make the LOLIcon folder at the root of ux0: also (only on my VitaTV though, on my Vita it happened automatically).

**Comment by kong2991** [comment]
Ok..so you suggest to move my whole tai folder to ur0:tai and change my config.txt as well. Why is that? Is it going to read from ur0 next time I boot?? I always have this mini heart attack everytime before doing one of this thing..

**Comment by kong2991** [comment]
Ohh wow never think about removing my mmc though. But I get it. I am using Enso, still scared to upgrade to 3.68 h-encore. Thanks though...but I still got green flash "There's an error loading...3"...If it's nothing then it's okay. Hope dev got this issue solve on next LOLIcon update.

**Comment by noradninja** [comment]
I hear you. What I want them to solve is it breaking Adrenaline- right now I have to disable the extension (by commenting it out with a #) and reboot the Vita, then undo it and do the same to re-enable it.

**Comment by kong2991** [comment]
I think it's already been solved. I just read the thread on reddit. Look for vitapiracy and search for lolicon. Read the whole comment, about 100 of em. I don't know what Adrenaline is... So far I only use maidump for some games and most is nonpdrm.

**Comment by noradninja** [comment]
The updated version is in this thread [https://github.com/dots-tb/LOLIcon/issues/3](url), just found it and its working great now. Adrenaline is a full PSP hardware emulator (so it loads up the UI and everything) for playing PSP/PS1 games and PSP HB. That combined with Vita HB/Dumps makes the Vita an absolute powerhouse of a console, with a massive library of games available to it.

![fullsizerender-1](https://user-images.githubusercontent.com/6692990/44630679-99947300-a92f-11e8-8d78-bf56d6249c98.jpeg)

**Comment by kong2991** [comment]
Oh wow... I read about this long time ago. I forgot, I try to install it but not everyone as helpful as today back then. So...meh... I got my PSP Go to play Type-0. Why no one brought Type-0 on Vita though, such a good game.

**Comment by noradninja** [comment]
Yeah...thats how I feel about the two awesome Silent Hill games we got on the PSP, and the rougelike in Silent Hill clothing we got on the Vita. Tis a shame.

**Comment by kong2991** [comment]
Nah it's fine I have my PSP for a good 5 years now. This bad boys still kicking. And my Vita is rock. And my PC...we...we don't talk about that...

**Comment by dots-tb** [comment]
I'm going to assume moving to ur0 will fix the issue. I hope.

**Comment by kong2991** [comment]
Nope it didn't fix the issue. As long as it doesn't mess up I'm good, no worries. Just keep delivering good stuff on my kick ass Vita...since Sony pretty much leave this poor system. Keep up the good work dev
